### PR TITLE
Finally merging to master

### PR DESCRIPTION
**Pull request by maybeec**
We should eventually come to an OSS release to be able to use the PDF generation in build jobs.

fixing #9

### CODE REVIEW

**Comment by sjimenez77** [comment]
I have requested to @Jorge-Dacal to review this with @jdiazgon help next week.

**Comment by jdiazgon** [comment]
Seems correct to me, it should be merged.

**Comment by jdiazgon** [comment]
@sjimenez77 and @maybeec, changes we added:

- Special characters can now be used in titles (¡!¿?.')
- Travis now tests the generation of pdfs by using the CobiGen wiki.

**Comment by jdiazgon** [comment]
The problem related to the strange characters that were showing up, was that asciidoctor had a [bug](https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/305) on version `1.5.5`.  Now it has been fixed and I have not seen any strange character.

Links are working, however there is a constraint. If you want to reference an external asciidoc file (the complete file and not a section  of it) then the level 0 title must be equal to the file name. Example:

```asciidoc
= FileName
```

I have deployed version 1.0.0 to https://devon.s2-eu.capgemini.com/nexus/content/repositories/releases/io/oasp/java/

**Comment by maybeec** [comment]
Great! Thank you very much @jdiazgon

**Comment by maybeec** [comment]
@jdiazgon as you already deployed, please merge and tag the version in the repository. Also please close the other PR, which is non-sense then.

**Comment by jdiazgon** [comment]
@maybeec Unfortunately, I do not have permission to merge this. @hohwille could you review the new changes and if it is okay for you, approve the merge?

**Pull request merged**
